### ISSUE TITLE
question about performance in Lambda

### ISSUE THREAD

**Issue by jvsteiner** [ventz/whisper-openai-container#1]
AFAIK Lambda doesn't provide access to GPU resources - how do these workflows run? Is it slow?

**Comment by ventz** [comment]
Hi @jvsteiner - Thats correct, Lambda's do not give GPU, thats why I built an"hybrid" that can be deployed as a standalone container for EC2/Fargate/external providers. 

As an aside - Modal's cloud does let you run Functions on GPU backed containers. Imo, Modal also makes it 10x easier to run lambda/container (mixed, or each) workloads. 

As far as speed on AWS Lambda's - my use case seems to fit within the 15 min max execution that Lambda provides.

**Comment by jvsteiner** [comment]
checking out modal now - looks like a gamechanger...
